#!/bin/sh
set -e

script="$0"
while [ -L "$script" ]; do
  link="$(readlink "$script")"
  case "$link" in
    /*) script="$link" ;;
    *) script="$(dirname "$script")/$link" ;;
  esac
done

resources="$(cd "$(dirname "$script")/.." && pwd)"
ELECTRON_RUN_AS_NODE=1 exec "$resources/../MacOS/NoteRepo" "$resources/app.asar/bin/noterepo.cjs" "$@"
